version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:suasenha@db:5432/mydatabase
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  postgres_data:
