# Usando a imagem oficial do PostgreSQL como base
FROM postgres:15

# Definindo variáveis de ambiente para configuração do banco de dados
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=suasenha
ENV POSTGRES_DB=mydatabase

# Expondo a porta padrão do PostgreSQL
EXPOSE 5432

